name: 'Chisel-actions'
description: 'Run chisel command on chisel3-tools'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'test'
outputs:
  time: # id of output
    description: 'The time we greeted you'
uses: actions/checkout@v1
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
